language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - cd $TRAVIS_BUILD_DIR/udacity-restapi-user
  - docker build -t "$DOCKER_USER"/restapi-user:latest .
  - cd $TRAVIS_BUILD_DIR/udacity-restapi-feed
  - docker build -t "$DOCKER_USER"/restapi-feed:latest .
  - cd $TRAVIS_BUILD_DIR/udacity-frontend
  - docker build -t "$DOCKER_USER"/frontend:latest .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push "$DOCKER_USER"/restapi-user:latest
  - docker push "$DOCKER_USER"/restapi-feed:latest
  - docker push "$DOCKER_USER"/frontend:latest