language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - cd $TRAVIS_BUILD_DIR/udacity-c3-restapi-user
  - docker build -t sgurpartap675/restapi-user:latest .
  - cd $TRAVIS_BUILD_DIR/udacity-c3-restapi-feed
  - docker build -t sgurpartap675/restapi-feed:latest .
  - cd $TRAVIS_BUILD_DIR/udacity-c3-frontend
  - docker build -t sgurpartap675/frontend:latest .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" docker.io
  - docker push sgurpartap675/restapi-user:latest
  - docker push sgurpartap675/restapi-feed:latest
  - docker push sgurpartap675/frontend:latest
