language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - cd $TRAVIS_BUILD_DIR/udagram-api
  - docker build -t "$DOCKER_USER"/api:latest .
  - cd $TRAVIS_BUILD_DIR/project_gd
  - docker build -t "$DOCKER_USER"/project:latest .
  - cd $TRAVIS_BUILD_DIR/udagram-frontend
  - docker build -t "$DOCKER_USER"/frontend:latest .
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push "$DOCKER_USER"/api:latest
  - docker push "$DOCKER_USER"/project:latest
  - docker push "$DOCKER_USER"/frontend:latest