apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: project_gd
        image: sgurpartap675/project_gd
        ports:
        - containerPort: 80
      resources:
      limits:
        memory: 256Mi
        cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
